ARDUINO_DIR=/opt/arduino/arduino-1.0.1
ARDMK_DIR=/opt/arduino/arduino-make
AVR_TOOLS_DIR=/opt/arduino/arduino-1.0.1/hardware/tools/avr/
AVRDUDE_CONF=/opt/arduino/arduino-1.0.1/hardware/tools/avrdude.conf
#BOARD_TAG    = attiny2313
#BOARDS_TXT   = /home/akipp/sketchbook/hardware/attiny/boards.txt
ARDUINO_PORT = /dev/ttyACM0
BOARD_TAG    = atmega328
#ARDUINO_LIBS = CustomSoftwareSerial
#ARDUINO_VAR_PATH = /home/akipp/sketchbook/hardware/attiny/variants
ISP_PROG     = -c usbtiny #-B 1
ISP_PORT     = usb 
#EXTRA_CPPFLAGS = -D_SS_PCINT0_DISABLE
include /opt/arduino/arduino-make/arduino-mk/Arduino.mk
